from datetime import datetime
startTime = datetime.now()

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci1 = 1      # previous term in sequence
fibonacci2 = 2      # current term in sequence
fibonacci3 = 0      # placeholder
sum = 0             # sum of even-valued terms

while fibonacci2 < 4000000:
    if fibonacci2 % 2 == 0:
        sum += fibonacci2
    fibonacci3 = fibonacci1 + fibonacci2
    fibonacci1 = fibonacci2
    fibonacci2 = fibonacci3

print(sum)
print(datetime.now() - startTime)

# # # # # # # # # #
# Answer: 4613732 #
# Time: 0.001     #
# # # # # # # # # #
